### ISSUE TITLE
12.	The Influent Design Parameters and Effluent Design Parameters list has two lines coming together, which looks a little funny.  Can we use one continuous line instead?

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#12]
![image](https://user-images.githubusercontent.com/3256516/42771263-36390e6e-88ec-11e8-994f-5305d99810d1.png)

**Comment by phstanek** [comment]
As this cannot be tested in the ADP development version due to database changes, and changes to this report address multiple issues (issues 8, 9, and 12), I am presenting this screenshot for approval prior to uploading the updated report (SBRPrelimPkg1MAINPrimeNEW.rpt) to the APD live version:

![apd-top-apd-quick-wins_issue 12](https://user-images.githubusercontent.com/41307105/43201463-35961d64-8fde-11e8-864b-50ea6ae3a903.png)

**Comment by phstanek** [comment]
I tested this issue with Jakob Nowicki, and the updated report is now in the Live APD system.

Note that (2) report files had to be updated:
**SBRPrelimPkg1MAINPrimeNEW.rpt** - Used by the system when the SBR Prelim Package is selected
**SBRPrelimPkg1MAINPrimeCoverNEW.rpt** - Used by the system when the Design Cover Sheet for AquaPrime is selected (which then also selects the SBR Prelim Package)

**Comment by phstanek** [comment]
This issue has been resolved and can now be closed.
