### ISSUE TITLE
8.	The AquaPrime Filtration design report does not list units in the Influent Design Parameters or Effluent Design Parameters.  This applies to the SBR PrelimPackage, and filter summary reports.

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#8]
![image](https://user-images.githubusercontent.com/3256516/42771132-d1c3acaa-88eb-11e8-8077-e9eb40909455.png)

**Comment by phstanek** [comment]
As this cannot be tested in the ADP development version due to database changes, and changes to this report address multiple issues (issues 8, 9, and 12), I am presenting this screenshot for approval prior to uploading the updated report (SBRPrelimPkg1MAINPrimeNEW.rpt) to the APD live version:

![apd-top-apd-quick-wins_issue 8](https://user-images.githubusercontent.com/41307105/43201183-60c4cfcc-8fdd-11e8-91af-5879785860d8.png)

**Comment by phstanek** [comment]
I tested this issue with Jakob Nowicki, and the updated report is now in the Live APD system.

Note that (2) report files had to be updated:
**SBRPrelimPkg1MAINPrimeNEW.rpt** - Used by the system when the SBR Prelim Package is selected
**SBRPrelimPkg1MAINPrimeCoverNEW.rpt** - Used by the system when the Design Cover Sheet for AquaPrime is selected (which then also selects the SBR Prelim Package)

**Comment by phstanek** [comment]
This issue has been resolved and can now be closed.
