### ISSUE TITLE
9.	Add a colon after Bio/Chem Oxygen Demand in the list of design parameters.

### ISSUE THREAD

**Issue by chukon** [AquaAerobicSystemsInc/APD-Top-APD-Quick-Wins#9]
![image](https://user-images.githubusercontent.com/3256516/42771168-e8ce8e4c-88eb-11e8-86dc-f18406945f0a.png)

**Comment by phstanek** [comment]
As this cannot be tested in the ADP development version due to database changes, and changes to this report address multiple issues (issues 8, 9, and 12), I am presenting this screenshot for approval prior to uploading the updated report (SBRPrelimPkg1MAINPrimeNEW.rpt) to the APD live version:

![apd-top-apd-quick-wins_issue 9](https://user-images.githubusercontent.com/41307105/43201386-f75e4d96-8fdd-11e8-96d0-808431c2e631.png)

**Comment by phstanek** [comment]
I tested this issue with Jakob Nowicki, and the updated report is now in the Live APD system.  Colons were also added after Nitrogen in the influent and effluent sections.

Note that (2) report files had to be updated:
**SBRPrelimPkg1MAINPrimeNEW.rpt** - Used by the system when the SBR Prelim Package is selected
**SBRPrelimPkg1MAINPrimeCoverNEW.rpt** - Used by the system when the Design Cover Sheet for AquaPrime is selected (which then also selects the SBR Prelim Package)

**Comment by phstanek** [comment]
This issue has been resolved and can now be closed.
